apps/achievements/urls.py
from django.conf.urls import patterns, url
from .views import (SectionDetail,
                    CategoryDetail,
                    CategoryDetailData,
                    )


urlpatterns = patterns(
    'apps.achievements.views',
    url(r'^section/(?P<pk>\d+)/$',
        SectionDetail.as_view(),
        name='section_detail'),
    url(r'^category/(?P<pk>\d+)/$',
        CategoryDetail.as_view(),
        name='category_detail'),
    url(r'^category/(?P<pk>\d+)/data/$',
        CategoryDetailData.as_view(),
        name='category_detail_data'),
)

inlife/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.views.generic import ListView
from django.views.decorators.csrf import csrf_exempt
from app.views import *
from filebrowser.sites import site
admin.autodiscover()


urlpatterns = patterns(
    '',
    url(r'', include('apps.achievements.urls')),

    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^rules/$', RulesView.as_view(), name='rules'),
    url(r'^clear_cache/$', 'app.views.clear_cache', name='clear_cache'),
    url(r'^closesite/$', 'app.views.closesite', name='closesite'),
    url(r'^start/$', StartView.as_view(), name='start'),
    url(r'^ab_test/$', ABView.as_view(), name='ab_test'),
    url(r'^friends/', include('apps.friends.urls')),
    url(r'^mytrees/get_children/(?P<ach_id>\d+)$', GetAchievementChildren.as_view(), name='get_achivement_children'),
    #url(r'^mytrees/(?P<tree_pk>\d+)/(?P<pk>\d+)/$', UserAchievementDetailView.as_view(), name='user_achievement_detail'),
    url(r'^achievements/create/$', AchievementCreateView.as_view(), name='achievement_create'),
    url(r'^achievements/(?P<ach_id>\d+)/\?callback=(?P<callback>.+)$', 'app.views.achievement_detail', name='achievement_with_callback'),
    url(r'^achievements/(?P<ach_id>\d+)/$', 'app.views.achievement_detail', name='achievement'),
    url(r'^achievements/(?P<ach_id>\d+)/activate/$', 'app.views.activate_achievement', name='activate_achievement'),
    url(r'^achievements/(?P<ach_id>\d+)/unactivate/$', 'app.views.unactivate_achievement', name='unactivate_achievement'),
    url(r'^achievements/(?P<ach_id>\d+)/confirm/$', 'app.views.confirm_achievement', name='confirm_achievement'),
    url(r'^achievements/(?P<ach_id>\d+)/confirm/upload_photo/$', 'app.views.upload_proof_photo', name='upload_proof_photo'),
    url(r'^achievements/(?P<user_ach_id>\d+)/comment/$', CommentAchievementView.as_view(), name='comment_achievement'),
    url(r'^achievements/(?P<user_ach_id>\d+)/like/$', LikeAchievementView.as_view(), name='like_achievement'),
    url(r'^achievements/(?P<user_ach_id>\d+)/unlike/$', UnLikeAchievementView.as_view(), name='unlike_achievement'),
    url(r'^achievements/(?P<user_ach_id>\d+)/accept/$', AcceptAchievementView.as_view(), name='accept_achievement'),
    url(r'^achievements/(?P<user_ach_id>\d+)/delete/$', DeleteAchievementView.as_view(), name='delete_achievement'),
    url(r'^confirm/upload_temp_proof_photo/$', 'app.views.upload_temp_proof_photo', name='upload_temp_proof_photo'),
    url(r'^confirm/delete_temp_proof_photo/(?P<obj_id>\d+)/$',
        'app.views.delete_temp_proof_photo', name='delete_temp_proof_photo'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin_tools/', include('admin_tools.urls')),
    url(r'^settings/', include('lsettings.urls')),
    url(r'^proof/(?P<pk>\d+)/$', 'app.views.proof_vote', name='proof_vote'),

    url(r'^conversations/$', 'app.views.conversations', name='conversations'),
    url(r'^conversations/count/$', ConversationsCountView.as_view(), name='conversations_count'),
    url(r'^conversations/check$', 'app.views.conversations_check', name='conversations_check'),

    url(r'^comment/delete/(?P<obj_type>[\-\w]+)/(?P<pk>\d+)/$', CommentDeleteView.as_view(), name='comment_delete'),
    url(r'^ratings/$', RatingsView.as_view(), name='ratings'),
    url(r'^share/enquire_posting_vk/$', EnquireVKPosting.as_view(), name='enquire_posting_vk'),
    url(r'^share/vk_post_images/$', VKPostImages.as_view(), name='vk_post_images'),
    url(r'^soc_post_image/$', SocApiPostImage, name='soc_post_image'),
    url(r'^(?P<user_id>\d+)/achievement/(?P<pk>\d+)/$', UserAchievementConfirmedDetailView.as_view(), name='user_achievement_confirmed_detail'),
    url(r'^(?P<user_id>\d+)/achievement/(?P<pk>\d+)/vk_post_images/$', VKPostImages.as_view(), name='vk_post_images'),
    url(r'^(?P<user_id>\d+)/achievement/(?P<ach_id>\d+)/data/$', UserAchievmentDataView.as_view(), name='achievment_data'),

    url(r'^edit_achievement/(?P<pk>\d+)/$', AchievementEditView.as_view(), name='user_edit_achievement'),
    url(r'^achievements/create/(?P<user_id>\d+)/$', AchievementForUserCreateView.as_view(), name='create_achievement_for_user'),
    url(r'^userachievements/create/(?P<ach_id>\d+)/$', 'app.views.userachievement_create', name='userachievement_create'),

    url(r'^instagram/$', 'app.views.instagram', name='instagram'),
    url(r'^instagramback/$', 'app.views.instagramback', name='instagramback'),
    url(r'^nextphotos/$', 'app.views.nextphotos', name='nextphotos'),

    url(r'^(?P<user_id>\d+)/summary/$', 'app.views.summary', name='user_summary'),
    #(r'^search/', include('haystack.urls')),
    url(r'^search/$', SearchView.as_view(), name='search'),
    url(r'', include('users.urls')),
    url(r'', include('guide.urls')),
    url(r'', include('actions.urls')),
    url(r'^notifications/', include('notifications.urls')),
    url(r'^messages/', include('postman.urls')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^groups/', include('groups.urls')),
    url(r'', include('social_auth.urls')),
    #(r'^tinymce/', include('tinymce.urls')),
    #url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^fileupload/', include('fileupload.urls')),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    )
    
if settings.DEBUG:
    urlpatterns += patterns(
        '', url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                'document_root': settings.MEDIA_ROOT, }),
        )
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()
else:
    from django.shortcuts import render

    def handler_custom404(request, *args, **kwargs):
        return render(request, "404.html", {})

    def handler_custom500(request, *args, **kwargs):
        return render(request, "500.html", {})

    handler404 = 'inlife.urls.handler_custom404'
    handler500 = 'inlife.urls.handler_custom500'

apps/achievements/models.py
# -*- coding: utf-8 -*-
# возможно, стоит постепенно перенести сюда модели Achievement и UserAchievement из app

apps/app/forms.py
# coding: utf-8
from datetime import datetime, timedelta
from django import forms
from django.forms import extras
from django.forms.models import modelformset_factory
from django.forms.models import inlineformset_factory
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext_lazy as _
from django.template.defaultfilters import striptags
from registration.forms import RegistrationFormUniqueEmail
from app.const import SEX_CHOICES
from app.models import Proof, ProofPhoto, Achievement, UserAchievement, ProofPhoto
from image_cropping import ImageCropWidget, ImageRatioField, ImageCropField
from app.widgets import AppImageCropWidget
from tinymce.widgets import TinyMCE
from inlife.utils import AchieverFormMixin
from .widgets import IconColorWidget, WYSIWYGTextWidget
InLifeUser = get_user_model()

class ProofForm(forms.ModelForm):
    #cropping = forms.CharField(widget=forms.HiddenInput(), required=False)
    #ach_img = forms.CharField(widget=forms.HiddenInput())

    description = forms.CharField(widget=forms.TextInput(
        attrs={
            'rows': 14,
            'cols': 40,
            'class': u"form-control",
        }),
        required=False
     )

    class Meta:
        model = Proof
        fields = ('description', )


class SimpleProofPhotoForm(forms.Form):
    photo = forms.ImageField()


class ProofPhotoForm(forms.ModelForm):

    class Meta:
        model = ProofPhoto
        widgets = {
            'photo': ImageCropWidget,
            'position': forms.HiddenInput
        }

class BaseProofPhotoFormset(forms.models.BaseModelFormSet):
    def clean(self):
        if any(self.errors):
            return
        forms_count = len(self.forms) - len(self.deleted_forms)
        if forms_count < 1:
            for deleted_form in self.deleted_forms:
                deleted_form.fields['DELETE'] = False
            raise forms.ValidationError(u"Необходмио выбрать хотя бы одну картинку")

ProofPhotoFormset = modelformset_factory(ProofPhoto, formset=BaseProofPhotoFormset,
    form=ProofPhotoForm,
    fields=('photo','cropping','position'), can_delete=True, extra=0)

class ReplyForm(forms.Form):
    recipient = forms.IntegerField(widget=forms.HiddenInput())
    text = forms.CharField(widget=forms.Textarea(
        attrs={
            'class': u'form-control',
            'rows':"3",
            'cols':"15",
        }),
        label=u'Сообщение'
    )

    def clean_recipient(self):
        data = self.cleaned_data['recipient']
        if not data:
            raise forms.ValidationError()
        try:
            instance = InLifeUser.objects.get(id=data)
        except InLifeUser.DoesNotExist:
            raise forms.ValidationError()
        return instance

class ActionCommentForm(forms.Form):
    comment = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': u'add_comment',
            'placeholder':u'написать комментарий',
            'autocomplete': 'off',
        }),
    )

class CategoryActivateForm(forms.Form):
    def __init__(self, category=None, *args, **kwargs):
        super(CategoryActivateForm, self).__init__(*args, **kwargs)
        self._category = category
        self.max_intensity = category.time_to_complete * 3
        self.min_intensity = category.time_to_complete / 3
        if self.min_intensity < 1:
            self.min_intensity = 1
        self.fields['intensity'].widget.attrs['data-title'] = u"Максимум: %s" % self.max_intensity

    intensity = forms.IntegerField(widget=forms.TextInput(
        attrs={
            'class': "qty_hours hint form-control",
            'autocomplete': 'off',
            'maxlength':"2",
        }),
    )

    def clean(self):
        cleaned_data = super(CategoryActivateForm, self).clean()
        if 'intensity' in cleaned_data:
            intensity = cleaned_data['intensity']
            if intensity > self.max_intensity:
                self._errors['intensity'] = self.error_class(["Максимальная интенсивность: %s" % self.max_intensity ])
            if intensity < self.min_intensity:
                self._errors['intensity'] = self.error_class(["Минимальная интенсивность: %s" % self.min_intensity ])
        else:
            self._errors['intensity'] = self.error_class(["Необходимо указать интенсивность"])
        return cleaned_data
    
class AchievementAddForm(forms.ModelForm):                
    class Meta:
        model = Achievement
        widgets = {
            'points_weight': forms.HiddenInput,
            'time_to_complete': forms.HiddenInput,
            'stars_number': forms.HiddenInput
        }
        #fields 
        exclude = ('date', 'parent', )
        
    short_decscription = forms.CharField(widget=forms.Textarea(
        attrs={
            'rows': 4,
            'cols': 40,
            'class': u"form-control",
        }),
        required=False
    )
    description = forms.CharField(widget=forms.TextInput(
        attrs={
            'rows': 14,
            'cols': 40,
            'class': u"form-control",
        }),
        required=False,
    )    
    name = forms.CharField(widget=forms.TextInput(
        attrs={
            'placeholder': u'Введите название достижения',
            'class': u"form-control",
            'data-bind': "value: ach_name, valueUpdate: 'afterkeydown' "
        }),
    )
    cropping = forms.CharField(widget=forms.HiddenInput(), required=False)
    ach_img = forms.CharField(widget=forms.HiddenInput(), required=False)
    
    def clean_short_decscription(self):
        return striptags(self.cleaned_data['short_decscription'])

    def clean_description(self):
        return self.cleaned_data['description']


class AddAchievementToUserForm(AchievementAddForm):
    """Форма добавления достижения пользователю админом"""
    STATUS_CHOICES = (
        (UserAchievement.ACTIVE, u'Активированно'),
        (UserAchievement.RECEIVED, u'Получено'),
    )
    status = forms.ChoiceField(choices = STATUS_CHOICES, widget=forms.RadioSelect)
    comment = forms.CharField(required=False, widget=forms.TextInput(
        attrs={
            'class': u"form-control",
        }),)
    description = forms.CharField(widget=forms.TextInput(
        attrs={
            'rows': 14,
            'cols': 40,
            'class': u"form-control",
        }),
        required=False
     )
    short_decscription = forms.CharField(widget=forms.Textarea(
        attrs={
            'rows': 4,
            'cols': 40,
            'class': u"form-control",
        }),
        required=False
     )
    time_to_complete = forms.IntegerField(widget=forms.TextInput(
        attrs={
            'class': "qty_hours hint form-control",
            'autocomplete': 'off',
            'maxlength':"2",
        }),
    )
        
class AddAchievementToUserGenTreeForm(AchievementAddForm):   
    parent = forms.ModelChoiceField(queryset=Achievement.objects.filter(), empty_label=u'Выберите категорию')


class SearchForm(forms.Form):
    q = forms.CharField(required=False, label=_('Search'))


class UserAchievementCommentForm(forms.Form):
    comment = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': u'add_comment',
            'placeholder':u'написать комментарий',
            'autocomplete': 'off',
        }),
    )

apps/achievements/views.py
# -*- coding: utf-8 -*-
from django.views.generic import (DetailView, )
from rest_framework import generics
from rest_framework.response import Response
from apps.app.models import (Category, Achievement)
from .serializers import CategorySerializer


class SectionDetail(DetailView):
    """меню раздела - список подкатегорий"""
    model = Category
    context_object_name = 'section'
    template_name = 'section_detail.html'
    queryset = Category.objects.filter(level=0)

    def get_context_data(self, **kwargs):
        context = super(SectionDetail, self).get_context_data(**kwargs)
        context['subsections'] = self.object.get_descendants().filter(level__lt=3)
        return context


class CategoryDetail(DetailView):
    model = Category
    context_object_name = 'category'
    template_name = 'category_detail.html'
    queryset = Category.objects.filter(level=2)


class CategoryDetailData(generics.ListAPIView):
    serializer_class = CategorySerializer
    response = {"children": []}

    def get_queryset(self):
        parent_pk = self.kwargs['pk']
        return Category.objects.filter(
            parent_id=parent_pk
            ).prefetch_related('achievements')

    def get(self, reqest, *args, **kwargs):
        self.queryset = self.get_queryset()
        serializer = self.get_serializer(self.queryset, many=True)
        self.response["children"] = serializer.data
        return Response(self.response)

templates/achievement/achievement_confirm.html
{% extends 'base.html' %}
{% load inlife_tags staticfiles %}

{% block content %}
<!-- Modal -->
<form class="modal fade modal-cute instagram-modal" id="instagram-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <a href="#" class="close" data-dismiss="modal" aria-hidden="true">&times;</a>
        <img src="{% static 'img/instagram-logo.png' %}">
      </div>
    <div class="modal-body">
      {% if inst_photo %}
        <ul class="list-inline">
          {% for photo, thumb in inst_photo %}
            <li><img data-url="{{ photo }}" src="{{ thumb }}"/><div class="check icon-ok"></div></li>
          {% endfor %}
        </ul>
      {% endif %}
    </div>
    <div id="access_token" style="display: none;">{{ access_token }}</div>
    <div id="max_id" style="display: none;">{{ max_id }}</div>
    <div class="modal-footer">
      <a href="#" id="instgram_image" class="btn btn-primary" data-dismiss="modal" aria-hidden="true" >Прикрепить</a>
    </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</form><!-- /.modal -->
    
    <div class="media media-header">
      <div class="pull-left">
        {% achiv_span user_achievement %}

      </div>
      <div class="media-body">
        <h2>
            {% if user_achievement.is_active %}
                Подтверждение цели: «{{ user_achievement.achievement.name }}»
            {% else %}
                Изменение достижения: «{{ user_achievement.achievement.name }}»
            {% endif %}
        </h2>
      </div>
    </div>

    <form class="form-horizontal" action="{% url 'confirm_achievement' user_achievement.achievement.id %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% for hidden in form.hidden_fields %}
        {{ hidden }}
      {% endfor %}


       {# выбор вотографии  #}
  {# почему-то не включается через include  #}
    <div class="form-group">
      <link href="{% static 'image_cropping/css/jquery.Jcrop.min.css' %}" type="text/css" media="all" rel="stylesheet" />
      <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
      <script type="text/javascript" src="{% static 'image_cropping/js/jquery.Jcrop.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'image_cropping/image_cropping.js' %}"></script>
      <style> .jcrop-image { margin: 0 auto; } </style>

      {{ photo_formset.management_form }}
      <div class="col-xs-12 add-achiv-img-box photo_select">
        <div class="achiv_cover-box" id="achiv_cover">
        <p class="upload-message" style="display: none;">Идет загрузка фотографии...<span class="upload-progress"></span></p>
          <div id="photo_formsets_container">
            {% for photo_form in photo_formset %}
            <div class='proof_photo_form' id="photo_form_{{ forloop.counter0 }}" style="display: none;" >
              {{ photo_form.id }}
              <div style="display: none;" class='delete_input_wrap'>
                {{ photo_form.DELETE }}
              </div>
              <div style="display: none;" >
                {{ photo_form.photo }}
              </div>
              <div class='position_input_wrap'>
                {{ photo_form.position }}
              </div>
                {{ photo_form.cropping }}
            </div>
            {% endfor %}
          </div>
          
          <div class="not-first-condition {% if not photo_bool %}hide{% endif %}" >
            <span class="btn btn-black fileinput-button">
              <input type="hidden" id="id_proof_type" name="proof_type" value="1" />
              <span>
                <i class="icon-picture"></i> Выбрать фото <input id="id_select_photo" type="file" name="select_photo">
              </span>
            </span>
            {% if inst_photo %}
              <a href="#instagram-modal" data-toggle="modal" class="btn btn-black" ><i class="icon-instagram"></i> Фото из instagram</a>
            {% else %}
              <a href="{% url 'instagram' %}" class="btn btn-black" ><i class="icon-instagram"></i> Фото из instagram</a>
            {% endif %}
          </div>

          <div class="first-condition {% if photo_bool %}hide{% endif %}">
            <span class="btn btn-black fileinput-button">
              <input type="hidden" id="id_proof_type" name="proof_type" value="1" />
              <span>
                <i class="icon-picture"></i> Выбрать фото <input id="id_select_photo" type="file" name="select_photo">
              </span>
            </span>
            {% if inst_photo %}
              <a href="#instagram-modal" data-toggle="modal" class="btn btn-black" ><i class="icon-instagram"></i> Фото из instagram</a>
            {% else %}
              <a href="{% url 'instagram' %}" class="btn btn-black" ><i class="icon-instagram"></i> Фото из instagram</a>
            {% endif %}
          </div>
        </div>

        <ul class="photo_achiv photo_achiv-new unstyled">
          {% for photo_form in photo_formset %}
          <li>
            <div>
              <a class="icon-remove" href="#"></a>
              <img class="hint" src="{{ photo_form.photo.value.url }}"
                  style="width: 90px; height: 60px;"
                  form-id="#photo_form_{{ forloop.counter0 }}" data-placement="bottom" data-title="Сделать обложкой" data-index="0"></img>
            </div>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>

    {% for error in photo_formset.non_form_errors %}
      <br>
      <div class="alert alert-danger">
        <i class="icon-warning-sign"></i>
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ error }}
      </div>
    {% endfor %}

    {% for dict in photo_formset.errors %}
      {% for error in dict.values %}
        <br>
        <div class="alert alert-danger">
          <i class="icon-warning-sign"></i>
          <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ error }}
        </div>
      {% endfor %}
    {% endfor %}

    <script type="text/javascript">
        var proof_photo_upload_url = ("{% url 'upload_temp_proof_photo' %}").replace('//', '/');//(location.pathname + '/upload_photo/').replace('//', '/');
        $(document).ready(function() {
          if($("#instagram-modal .list-inline").length > 0) {
            $('#instagram-modal').modal('show');
          }
          engine.init(null, $(".list-inline"));
          $(".modal-body").scroll(function() {
            var height = $(".list-inline").height();
            if ($(this).scrollTop() + height >= $(".list-inline").height()) {
              engine.scrollPosition = $(window).scrollTop();
              engine.get();
            }
          });
        });
    </script>
    <script src="{% static 'js/proof_photos.js' %}"></script>
  {# /выбор вотографии  #}
      <div>
          <h3>Описание</h3>
            <div class="">
              {{ form.description }}
            </div>
        </div>
      <br><br>

      <hr/>

      
      <div style="margin-top: 10px">
        <input type="submit" class="btn btn-lg btn-primary pull-right" value="Сохранить"/>
      </div>
    </form>
{% endblock content %}
{% block js %}
<script type="text/javascript" src="{% static 'js/file-input.js' %}"></script>
<script type="text/javascript" src="{% static 'tiny_mce/tiny_mce.js' %}"></script>
<script type="text/javascript">
  tinymce.init({
    selector: "#id_description",
    plugins: "example, autolink, pagebreak, layer, table, save, advhr, advlink, emotions, iespell, inlinepopups, insertdatetime," +
             " preview, media, searchreplace, print, contextmenu, paste, directionality, fullscreen, noneditable," +
             " visualchars, nonbreaking, xhtmlxtras, template, advlist, youtube",
    theme_advanced_buttons1: "bold,italic,underline,strikethrough,|,formatselect,example,iespell,youtube",
    theme_advanced_path : false,
    theme_advanced_resizing : true,
    cleanup : false,
    convert_urls: false,
    theme_advanced_blockformats : "h1, h2, h4",
    extended_valid_elements: "h1, h2, h3, h4, h5, h6, iframe[src|title|width|height|allowfullscreen|frameborder|class|id|data-mce-src], object[classid|width|height|codebase|*], param[name|value|_value|*], embed[type|width|height|src|*]",
  });
</script>
{% endblock js%}

templates/achievement/achievement_detail_modal_confirmation.html
<!-- Modal confirmation-->
<div class="modal fade confirmation" id="confirmation" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	<p class="lead"></p>
        <ul class="nav nav-pills">
          <li class="active"><a href="#confirm_photo" data-toggle="pill" type="1"><i class="icon-camera"></i> Фото</a></li>
          <li><a href="#confirm_video" data-toggle="pill" type="2"><i class="icon-facetime-video"></i> Видео</a></li>
          <li><a href="#confirm_link" data-toggle="pill" type="3"><i class="icon-link"></i> Ссылка</a></li>
          <li><a href="#confirm_description" data-toggle="pill" type="4"><i class="icon-link"></i> Описание</a></li>
          <li class="danger">
	    <a href="#confirm_no" type="0"
	       {% if user_achievement.is_available_unfounded_proof.status %}
	       class="danger"
	       {% else %}
	       class="disabled"
	       reason="{{user_achievement.is_available_unfounded_proof.reason}}"
	       {% endif %} data-toggle="pill"
	       ><i class="icon-thumbs-down"></i> Без доказательств</a>
          </li>
        </ul>
      </div>
      <form class="align-center" method="post" action="{% url 'confirm_achievement' user_achievement.achievement.id %}"  enctype="multipart/form-data">
	<div class="modal-body">
          {% csrf_token %}
          <input type="hidden" id="id_proof_type" name="proof_type" value="1" />
	  <div class="tab-content">
	    <div class="tab-pane active" id="confirm_photo">
	      <div class="well">
                {{ photo_formset.management_form }}
                {% for photo_form in photo_formset %}
                {{ photo_form.photo }}
                {% endfor %}
	      </div>
	    </div>
	    <div class="tab-pane" id="confirm_video">
	      <div class="well">
		<input id="id_video" name="video" type="file" />
	      </div>
	    </div>
	    <div class="tab-pane" id="confirm_link">
	      <div class="well">
		<input type="text" id="inputEmail" class="input-lg form-control" placeholder="вставьте ссылку">
	      </div>
	    </div>

	    <div class="tab-pane" id="confirm_description">
	      <div class="well">
		<textarea id="id_description" name="description" rows="14" cols="40"></textarea>
	      </div>
	    </div>

	    <div class="tab-pane" id="confirm_no">
	      <div class="well">
                {% if user_achievement.is_available_unfounded_proof.status %}
                <p>Подтверждение без доказательств отнимает ваше доверие и делает вас пожизненным неудачником. Вы точно хотите этого?</p>
                {% else %}
                <p>{{user_achievement.is_available_unfounded_proof.reason}}</p>
                {% endif %}
	      </div>
	    </div>
	  </div>
	</div>
	<div class="modal-footer">
	  <button type="button" class="btn btn-default" data-dismiss="modal">Отменить</button>
	  <input type="submit" name="" class="btn btn-primary" id="id_submit" value="Подтвердить" />
          <script type="text/javascript">
                    $('#confirmation a[data-toggle="pill"]').on('show.bs.tab', function (e) {
                        var is_disabled = $(e.target).hasClass('disabled');
                        if (is_disabled) {
                            $('#id_submit').attr("disabled", "disabled");
                        }
                        else{
                            $('#id_submit').removeAttr("disabled");
                        }
                        var proof_type = $(e.target).attr("type");
                        $('input[name=proof_type]').val(proof_type);
                    });
          </script>
	</div>
      </form>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

templates/achievement/achiv_link.html
<a class="achiv achiv-link {{ a_class }}" href="{{ href }}" {% if data_title %}data-toggle="tooltip" data-title="{{data_title}}"{% endif %}>
    <span>
    {% for i in stars_range %}
        {% if forloop.last and forloop.counter == 3 %}
            {# небольшой хак, чтобы верстка при 3х звёздах была красивее #}
            <br>
        {% endif %}
        <i class="icon-star"></i>
    {% endfor %}
    </span>
</a>